### ISSUE TITLE
假的，，，首先不跨域，其次django登录后居然不给cas发消息，cas认证使用django自带认证？？？你这也叫单点登录？看起来高大上cas被你用得稀碎

### ISSUE THREAD

**Issue by psjwohoo** [cangelzz/cas-demo-django-server#4]
首先不跨域，其次django登录后居然不给cas发消息，cas认证使用django自带认证？？？你这也叫单点登录？看起来高大上cas被你用得稀碎

**Comment by psjwohoo** [comment]
表面跨域 实际用的同一套数据库同一个管理平台，首次登录应该给center发送消息。。这些全都没有，，，

**Comment by cangelzz** [comment]
技术讨论就讨论，你这上来就找茬儿是啥意思呢？这套我就是我给公司部署完单拿出来的非常精简的一部分了，其他需求你需要的话自己加呗
